### ISSUE TITLE
Ludum Dare - TO DO list

### ISSUE THREAD

**Issue by Florian-DELRIEU** [AngryCyboot/LD52#3]
- [x] #8
- [x] S'assurer que les colons morts ne travaillent pas !
- [x] Refaire l'agence des bâtiments et des colons
  - [x] Colons
  - [x] Batiments
- [x] #6
- [x] Corriger les zones d'effets des batiments
  - Les gros batiments on les memes zones d'effets que les petits ce qui oblige le joueurs a placer les colons bien au centre
- [x]  Le manque de certaines ressources ne tuent pas les colons (eau, oxy)
- [x] #7

**Comment by AngryCyboot** [comment]
je finis les stocks apres faudra se réunir pour l'équilibrage
